'use client';
import * as React from 'react';
import { ApiClientError } from '@/lib/api';
import { saveApplication, submitApplication, type JournalApplicationInput } from '@/lib/journal-api';
const services = ['AI 标准解读包', '批量导入与材料整理', '专业审核', '持续运营与基础统计'];
const declaration = '我确认拥有或已取得提交上述信息及后续材料处理所需的授权，并理解公开范围需逐篇确认。';
const empty: JournalApplicationInput = { nameZh: '', nameEn: '', pIssn: '', eIssn: '', websiteUrl: '', publisherName: '', sponsorName: '', subjects: [], description: '', logoUrl: '', applicantName: '', applicantTitle: '', applicantEmail: '', representationEvidence: '', plannedArticleCount: 0, requestedServices: [], rightsDeclaration: '', rightsDeclarationVersion: 'v1.0' };
export function JournalApplicationForm() { const [form, setForm] = React.useState(empty); const [id, setId] = React.useState<string>(); const [revision, setRevision] = React.useState<number>(); const [message, setMessage] = React.useState(''); const [saving, setSaving] = React.useState(false); const set = (key: keyof JournalApplicationInput, value: unknown) => setForm((old) => ({ ...old, [key]: value })); const persist = async (submit = false) => { setSaving(true); setMessage(''); try { const saved = await saveApplication({ ...form, ...(id ? { revision } : {}) }, id); setId(saved.application.id); setRevision(saved.application.revision); if (submit) await submitApplication(saved.application.id, { revision: saved.application.revision, submissionKey: crypto.randomUUID() }); setMessage(submit ? '申请已提交。平台核验后会在此显示处理结果。' : '草稿已保存。'); } catch (e) { if (e instanceof ApiClientError && e.status === 401) { window.location.assign('/auth/login?returnTo=%2Fjournals%2Fapply'); return; } setMessage(e instanceof Error ? e.message : '保存失败，请重试。'); } finally { setSaving(false); } };
 const field = (key: keyof JournalApplicationInput, label: string, required = false, type = 'text') => <label className="grid gap-2 text-sm"><span>{label}{required ? ' *' : ''}</span><input required={required} type={type} value={String(form[key] ?? '')} onChange={(e) => set(key, type === 'number' ? Number(e.target.value) : e.target.value)} className="min-h-11 border border-os-rule-paper bg-transparent px-3" /></label>;
 return <form className="mt-8 grid gap-8" onSubmit={(e) => { e.preventDefault(); void persist(true); }}><fieldset className="grid gap-4 border-0 p-0"><legend className="mb-3 text-xl">期刊与主办信息</legend><div className="grid gap-4 sm:grid-cols-2">{field('nameZh', '中文刊名', true)}{field('nameEn', '英文刊名')}{field('pIssn', 'p-ISSN')}{field('eIssn', 'e-ISSN')}{field('websiteUrl', '期刊官网', true, 'url')}{field('publisherName', '出版者或主管单位', true)}{field('sponsorName', '主办单位')}{field('plannedArticleCount', '计划处理论文数', false, 'number')}</div><label className="grid gap-2 text-sm">学科（用逗号分隔）<input className="min-h-11 border border-os-rule-paper bg-transparent px-3" onChange={(e) => set('subjects', e.target.value.split(',').map((x) => x.trim()).filter(Boolean))} /></label><label className="grid gap-2 text-sm">期刊简介 *<textarea required rows={5} value={form.description} onChange={(e) => set('description', e.target.value)} className="border border-os-rule-paper bg-transparent p-3" /></label></fieldset><fieldset className="grid gap-4 border-0 p-0"><legend className="mb-3 text-xl">申请人与代表依据</legend><div className="grid gap-4 sm:grid-cols-2">{field('applicantName', '姓名', true)}{field('applicantTitle', '职务', true)}{field('applicantEmail', '工作邮箱', true, 'email')}</div><label className="grid gap-2 text-sm">可代表期刊的依据 *<textarea required rows={4} value={form.representationEvidence} onChange={(e) => set('representationEvidence', e.target.value)} className="border border-os-rule-paper bg-transparent p-3" /></label></fieldset><fieldset className="grid gap-3 border-0 p-0"><legend className="mb-2 text-xl">拟申请服务</legend>{services.map((service) => <label className="flex gap-2" key={service}><input type="checkbox" checked={form.requestedServices.includes(service)} onChange={(e) => set('requestedServices', e.target.checked ? [...form.requestedServices, service] : form.requestedServices.filter((v) => v !== service))} />{service}</label>)}</fieldset><label className="flex gap-3 border-t border-os-rule-paper pt-5 text-sm"><input required type="checkbox" checked={form.rightsDeclaration === declaration} onChange={(e) => set('rightsDeclaration', e.target.checked ? declaration : '')} />{declaration}</label>{message ? <p role="status">{message}</p> : null}<div className="flex flex-wrap gap-3"><button type="button" disabled={saving} className="min-h-11 border border-os-rule-paper px-5" onClick={() => void persist(false)}>保存草稿</button><button disabled={saving} className="min-h-11 bg-accent-primary-strong px-5 font-semibold text-os-black-0" type="submit">提交核验申请</button></div></form>; }
